name: Deploy Reveal.js Presentation

permissions:
  contents: write

on:
  push:
    branches:
      - "main"
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    concurrency:
      group: ${{ github.head_ref || github.run_id }}
      cancel-in-progress: true
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Install dependencies (if needed for Reveal.js customization)
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23"

      - name: Install dependencies
        run: |
          if [ -f package.json ]; then
            npm install
          fi

      # Build the presentation (if a build step is required)
      - name: Build Presentation
        run: |
          if [ -f package.json ]; then
            npm run build
          fi

      # Copy the necessary presentation files to the output directory
      - name: Prepare Presentation Files
        run: |
          mkdir -p out
          cp -R ./dist ./out

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: s0/git-publish-subdir-action@develop
        env:
          SQUASH_HISTORY: true
          REPO: self
          BRANCH: gh-pages # The branch name where you want to push the assets
          FOLDER: out # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Deploy Reveal.js Presentation: ({sha}) {msg}" # The commit message
